// src/components/Background.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useMainStore } from "@/store";
import { useSiteContentStore } from "@/stores/siteContent";
import type { BackgroundEffect } from "@/typings/store";
import type { WallpaperContentConfig } from "@/typings/siteContent";
import { initSnowfall, closeSnowfall } from "@/utils/season/snow";
import { initFirefly, closeFirefly } from "@/utils/season/firefly";
import { initLantern, closeLantern } from "@/utils/season/lantern";
import { initMeteor, closeMeteor } from "@/utils/season/meteor";
import { toast } from "@/ui/toast";
import "@/components/Background.scss";

interface Props {
  onLoadComplete: () => void;
  onImageLoaded: (image: HTMLImageElement) => void;
}

interface OnlineWallpaper { imageUrl: string; downloadUrl: string }

const defaultConfig: WallpaperContentConfig = {
  version: 1,
  desktop: { count: 10, pattern: "/images/background{id}.jpg", fallback: "/images/background1.jpg" },
  mobile: { count: 2, pattern: "/images/phone/backgroundphone{id}.jpg", fallback: "/images/phone/backgroundphone1.jpg" },
};

const preloadImage = (url: string, timeout = 12000) => new Promise<HTMLImageElement | null>((resolve) => {
  const image = new Image();
  image.decoding = "async";
  let settled = false;
  const finish = (result: HTMLImageElement | null) => {
    if (settled) return;
    settled = true;
    window.clearTimeout(timeoutId);
    image.onload = null;
    image.onerror = null;
    resolve(result);
  };
  const timeoutId = window.setTimeout(() => finish(null), timeout);
  image.onload = async () => {
    try { await image.decode(); } catch { /* 图像本身仍可用。 */ }
    finish(image);
  };
  image.onerror = () => finish(null);
  image.src = url;
});

const lunarNewYearRanges: Record<number, [string, string]> = {
  2026: ["2026-02-10", "2026-03-03"], 2027: ["2027-01-30", "2027-02-20"],
  2028: ["2028-01-19", "2028-02-10"], 2029: ["2029-02-06", "2029-02-27"],
  2030: ["2030-01-27", "2030-02-17"],
};

const automaticEffects = (date = new Date()): BackgroundEffect[] => {
  const result: BackgroundEffect[] = [];
  const month = date.getMonth() + 1;
  const hour = date.getHours();
  if (hour >= 19 || hour < 6) result.push("meteor");
  if ([12, 1, 2].includes(month)) result.push("snow");
  if ([6, 7, 8].includes(month) && (hour >= 19 || hour < 6)) result.push("firefly");
  const range = lunarNewYearRanges[date.getFullYear()];
  const today = date.toISOString().slice(0, 10);
  if (range && today >= range[0] && today <= range[1]) result.push("lantern");
  return result;
};

const closeAllEffects = () => { closeMeteor(); closeSnowfall(); closeFirefly(); closeLantern(); };

export default function Background({ onLoadComplete, onImageLoaded }: Props) {
  const backgroundShow = useMainStore((state) => state.backgroundShow);
  const coverType = useMainStore((state) => state.coverType);
  const wallpaperLocalId = useMainStore((state) => state.wallpaperLocalId);
  const autoInterval = useMainStore((state) => state.autoBGSwitchInterval);
  const effectsMode = useMainStore((state) => state.effectsMode);
  const selectedEffects = useMainStore((state) => state.selectedEffects);
  const config = useSiteContentStore((state) => state.snapshot.sections.wallpaper || defaultConfig);
  const wallpaperRevision = useSiteContentStore((state) => state.snapshot.sectionRevisions.wallpaper);
  const [mobile, setMobile] = useState(() => window.matchMedia("(max-width: 720px)").matches);
  const collection = mobile ? config.mobile : config.desktop;
  const [currentUrl, setCurrentUrl] = useState<string | null>(null);
  const [nextUrl, setNextUrl] = useState<string | null>(null);
  const [transitioning, setTransitioning] = useState(false);
  const [blurringIn, setBlurringIn] = useState(false);
  const [solidFallback, setSolidFallback] = useState(false);
  const [downloadUrl, setDownloadUrl] = useState<string | null>(null);
  const currentRef = useRef<string | null>(null);
  const sequence = useRef(0);
  const initialComplete = useRef(false);
  const loading = useRef(false);
  const controller = useRef<AbortController | null>(null);
  const timers = useRef<number[]>([]);

  const clearTimers = useCallback(() => {
    timers.current.forEach((timer) => window.clearTimeout(timer));
    timers.current = [];
  }, []);

  const finishInitial = useCallback(() => {
    useMainStore.getState().setImgLoadStatus(true);
    if (initialComplete.current) return;
    initialComplete.current = true;
    queueMicrotask(onLoadComplete);
  }, [onLoadComplete]);

  const activateSolidFallback = useCallback((requestId: number) => {
    if (requestId !== sequence.current) return;
    clearTimers();
    currentRef.current = null;
    setCurrentUrl(null); setNextUrl(null); setTransitioning(false); setBlurringIn(false);
    setSolidFallback(true); setDownloadUrl(null);
    finishInitial();
  }, [clearTimers, finishInitial]);

  const loadWallpaper = useCallback(async (source = coverType, temporaryId?: number) => {
    const requestId = ++sequence.current;
    controller.current?.abort();
    const requestController = new AbortController();
    controller.current = requestController;
    loading.current = true;
    useMainStore.getState().patch({ wallpaperMaxId: collection.count });
    const localUrl = (id: number) => collection.pattern.replace("{id}", String(id));
    const randomId = () => Math.floor(Math.random() * collection.count) + 1;
    let candidate: string;
    let resolvedDownload: string;

    if (source === 0) {
      const preferred = temporaryId ?? wallpaperLocalId ?? randomId();
      if (!Number.isInteger(preferred) || preferred < 1 || preferred > collection.count) {
        toast.error(`当前设备的壁纸 ID 应在 1–${collection.count} 之间，已改为随机`);
        candidate = localUrl(randomId());
      } else candidate = localUrl(preferred);
      resolvedDownload = candidate;
    } else {
      try {
        const sourceName = source === 1 ? "bing" : source === 2 ? "wallhaven" : "wallhaven-anime";
        const response = await fetch(`/api/wallpaper?source=${sourceName}`, {
          headers: { accept: "application/json" }, cache: "no-store", signal: requestController.signal,
        });
        if (!response.ok) throw new Error(`在线壁纸接口返回 ${response.status}`);
        const value = await response.json() as Partial<OnlineWallpaper>;
        if (!value.imageUrl || !value.downloadUrl) throw new Error("在线壁纸响应格式无效");
        candidate = value.imageUrl; resolvedDownload = value.downloadUrl;
      } catch (error) {
        if (requestController.signal.aborted || requestId !== sequence.current) return;
        console.error("无法获取在线壁纸，使用本地 fallback：", error);
        candidate = collection.fallback; resolvedDownload = candidate;
        toast.error("在线壁纸加载失败，已切换到本地壁纸");
      }
    }

    let image = await preloadImage(candidate);
    let finalUrl = candidate;
    if (!image) {
      image = await preloadImage(collection.fallback);
      finalUrl = collection.fallback;
      resolvedDownload = finalUrl;
    }
    if (requestId !== sequence.current) return;
    if (!image) {
      toast.error("本地壁纸也无法加载，已使用纯色背景");
      activateSolidFallback(requestId);
      return;
    }
    setSolidFallback(false); setDownloadUrl(resolvedDownload); onImageLoaded(image);
    if (!currentRef.current || window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      clearTimers(); currentRef.current = finalUrl; setCurrentUrl(finalUrl); setNextUrl(null);
      setTransitioning(false); setBlurringIn(false); finishInitial();
    } else {
      setNextUrl(finalUrl); setTransitioning(true); setBlurringIn(false);
      timers.current.push(window.setTimeout(() => requestId === sequence.current && setBlurringIn(true), 30));
      timers.current.push(window.setTimeout(() => {
        if (requestId !== sequence.current) return;
        currentRef.current = finalUrl; setCurrentUrl(finalUrl); setNextUrl(null);
        setTransitioning(false); setBlurringIn(false);
      }, 850));
    }
    loading.current = false;
  }, [activateSolidFallback, clearTimers, collection, coverType, finishInitial, onImageLoaded, wallpaperLocalId]);

  useEffect(() => {
    const query = window.matchMedia("(max-width: 720px)");
    const change = () => setMobile(query.matches);
    query.addEventListener("change", change);
    return () => query.removeEventListener("change", change);
  }, []);

  useEffect(() => { void loadWallpaper(); }, [loadWallpaper, wallpaperRevision]);

  useEffect(() => useMainStore.subscribe(
    (state) => state.sBGCount,
    (value) => {
      if (!value || useMainStore.getState().coverType !== 0) return;
      useMainStore.getState().patch({ sBGCount: null });
      void loadWallpaper(0, Number(value));
    },
  ), [loadWallpaper]);

  useEffect(() => {
    const milliseconds = ({ 0: 0, 1: 15000, 2: 30000, 3: 45000 } as Record<number, number>)[autoInterval] || 0;
    if (!milliseconds) return;
    const timer = window.setInterval(() => !document.hidden && !loading.current && void loadWallpaper(), milliseconds);
    return () => window.clearInterval(timer);
  }, [autoInterval, loadWallpaper]);

  useEffect(() => {
    const apply = () => {
      if (document.hidden || window.matchMedia("(prefers-reduced-motion: reduce)").matches || effectsMode === "off") {
        closeAllEffects(); return;
      }
      const desired = new Set<BackgroundEffect>(effectsMode === "manual" ? selectedEffects : automaticEffects());
      desired.has("meteor") ? initMeteor() : closeMeteor();
      desired.has("snow") ? initSnowfall() : closeSnowfall();
      desired.has("firefly") ? initFirefly() : closeFirefly();
      desired.has("lantern") ? initLantern() : closeLantern();
    };
    apply();
    const refresh = window.setInterval(apply, 30 * 60 * 1000);
    document.addEventListener("visibilitychange", apply);
    return () => { window.clearInterval(refresh); document.removeEventListener("visibilitychange", apply); closeAllEffects(); };
  }, [effectsMode, selectedEffects]);

  useEffect(() => () => {
    sequence.current += 1; controller.current?.abort(); clearTimers(); closeAllEffects();
  }, [clearTimers]);

  const coverClass = useMemo(() => `cover${backgroundShow ? " show" : ""}${solidFallback ? " solid-fallback" : ""}`, [backgroundShow, solidFallback]);
  return (
    <div className={coverClass}>
      {currentUrl && !solidFallback && <img src={currentUrl} className={`bg current${transitioning ? " blur-out" : ""}`} alt="" aria-hidden="true" onError={() => activateSolidFallback(++sequence.current)} />}
      {nextUrl && transitioning && <img src={nextUrl} className={`bg next${blurringIn ? " blur-in" : ""}`} alt="" aria-hidden="true" />}
      <div className={`gray${backgroundShow ? " o-hidden" : ""}`} />
      {backgroundShow && downloadUrl && <a className="down" href={downloadUrl} target="_blank" rel="noopener noreferrer">下载壁纸</a>}
    </div>
  );
}

// src/components/Background.vue
<template>
  <div class="cover" :class="{ show: store.backgroundShow, 'solid-fallback': useSolidFallback }">
    <img
      v-if="currentBgUrl && !useSolidFallback"
      :src="currentBgUrl"
      :class="['bg', 'current', { 'blur-out': isTransitioning }]"
      alt=""
      aria-hidden="true"
      @error="handleCommittedImageError"
    />
    <img
      v-if="nextBgUrl && isTransitioning"
      :src="nextBgUrl"
      :class="['bg', 'next', { 'blur-in': isBlurringIn }]"
      alt=""
      aria-hidden="true"
    />
    <div :class="store.backgroundShow ? 'gray o-hidden' : 'gray'" />
    <Transition name="fade" mode="out-in">
      <a v-if="store.backgroundShow && downloadUrl" class="down" :href="downloadUrl" target="_blank"
        rel="noopener noreferrer">
        下载壁纸
      </a>
    </Transition>
  </div>
</template>

<script setup lang="ts">
import { Error as ErrorIcon } from "@icon-park/vue-next";
import { mainStore } from "@/store";
import { useSiteContentStore } from "@/stores/siteContent";
import type { BackgroundEffect } from "@/typings/store";
import type { WallpaperContentConfig } from "@/typings/siteContent";
import { initSnowfall, closeSnowfall } from "@/utils/season/snow";
import { initFirefly, closeFirefly } from "@/utils/season/firefly";
import { initLantern, closeLantern } from "@/utils/season/lantern";
import { initMeteor, closeMeteor } from "@/utils/season/meteor";

interface OnlineWallpaper {
  imageUrl: string;
  downloadUrl: string;
}

const defaultConfig: WallpaperContentConfig = {
  version: 1,
  desktop: {
    count: 10,
    pattern: "/images/background{id}.jpg",
    fallback: "/images/background1.jpg",
  },
  mobile: {
    count: 2,
    pattern: "/images/phone/backgroundphone{id}.jpg",
    fallback: "/images/phone/backgroundphone1.jpg",
  },
};

const store = mainStore();
const siteContent = useSiteContentStore();
const emit = defineEmits<{
  loadComplete: [];
  imageLoaded: [image: HTMLImageElement];
}>();

const currentBgUrl = ref<string | null>(null);
const nextBgUrl = ref<string | null>(null);
const isTransitioning = ref(false);
const isBlurringIn = ref(false);
const useSolidFallback = ref(false);
const currentDownloadUrl = ref<string | null>(null);
const config = computed(() => siteContent.sections.wallpaper || defaultConfig);
const isLoading = ref(false);
const hasCompletedInitialLoad = ref(false);

let requestSequence = 0;
let transitionStartTimer: number | null = null;
let transitionEndTimer: number | null = null;
let autoSwitchTimer: number | null = null;
let effectRefreshTimer: number | null = null;
let wallpaperController: AbortController | null = null;

const deviceQuery = window.matchMedia("(max-width: 720px)");
const reducedMotionQuery = window.matchMedia("(prefers-reduced-motion: reduce)");

const activeCollection = computed(() => {
  return deviceQuery.matches ? config.value.mobile : config.value.desktop;
});

const downloadUrl = computed(() => useSolidFallback.value ? null : currentDownloadUrl.value);

const localUrl = (id: number) => activeCollection.value.pattern.replace("{id}", String(id));

const randomLocalId = () => {
  const count = activeCollection.value.count;
  return Math.floor(Math.random() * count) + 1;
};

const resolveLocalCandidate = (temporaryId?: number) => {
  const preferredId = temporaryId ?? store.wallpaperLocalId ?? randomLocalId();
  if (!Number.isInteger(preferredId) || preferredId < 1 || preferredId > activeCollection.value.count) {
    ElMessage.error(`当前设备的壁纸 ID 应在 1–${activeCollection.value.count} 之间，已改为随机`);
    return localUrl(randomLocalId());
  }
  return localUrl(preferredId);
};

const resolveOnlineCandidate = async (source: number, signal: AbortSignal): Promise<OnlineWallpaper> => {
  const sourceName = source === 1 ? "bing" : source === 2 ? "wallhaven" : "wallhaven-anime";
  const response = await fetch(`/api/wallpaper?source=${sourceName}`, {
    headers: { accept: "application/json" },
    cache: "no-store",
    signal,
  });
  if (!response.ok) throw new Error(`在线壁纸接口返回 ${response.status}`);
  const payload: unknown = await response.json();
  if (!payload || typeof payload !== "object") throw new Error("在线壁纸响应格式无效");
  const value = payload as Record<string, unknown>;
  if (typeof value.imageUrl !== "string" || typeof value.downloadUrl !== "string") {
    throw new Error("在线壁纸响应缺少图片地址");
  }
  return { imageUrl: value.imageUrl, downloadUrl: value.downloadUrl };
};

const preloadImage = (url: string, timeout = 12000) => {
  return new Promise<HTMLImageElement | null>((resolve) => {
    const image = new Image();
    image.decoding = "async";
    let settled = false;
    const finish = (result: HTMLImageElement | null) => {
      if (settled) return;
      settled = true;
      window.clearTimeout(timeoutId);
      image.onload = null;
      image.onerror = null;
      resolve(result);
    };
    const timeoutId = window.setTimeout(() => finish(null), timeout);
    image.onload = async () => {
      try {
        await image.decode();
      } catch {
        // 部分浏览器在 onload 后仍会拒绝 decode，图像本身依然可用。
      }
      finish(image);
    };
    image.onerror = () => finish(null);
    image.src = url;
  });
};

const clearTransitionTimers = () => {
  if (transitionStartTimer !== null) window.clearTimeout(transitionStartTimer);
  if (transitionEndTimer !== null) window.clearTimeout(transitionEndTimer);
  transitionStartTimer = null;
  transitionEndTimer = null;
};

const finishInitialLoad = () => {
  store.setImgLoadStatus(true);
  if (hasCompletedInitialLoad.value) return;
  hasCompletedInitialLoad.value = true;
  nextTick(() => emit("loadComplete"));
};

const commitImage = async (
  url: string,
  image: HTMLImageElement,
  sequence: number,
  resolvedDownloadUrl = url,
) => {
  if (sequence !== requestSequence) return;
  useSolidFallback.value = false;
  currentDownloadUrl.value = resolvedDownloadUrl;
  emit("imageLoaded", image);

  if (!currentBgUrl.value || reducedMotionQuery.matches) {
    clearTransitionTimers();
    currentBgUrl.value = url;
    nextBgUrl.value = null;
    isTransitioning.value = false;
    isBlurringIn.value = false;
    finishInitialLoad();
    return;
  }

  nextBgUrl.value = url;
  isTransitioning.value = true;
  isBlurringIn.value = false;
  await nextTick();
  transitionStartTimer = window.setTimeout(() => {
    if (sequence === requestSequence) isBlurringIn.value = true;
  }, 30);
  transitionEndTimer = window.setTimeout(() => {
    if (sequence !== requestSequence) return;
    currentBgUrl.value = url;
    nextBgUrl.value = null;
    isTransitioning.value = false;
    isBlurringIn.value = false;
  }, 850);
};

const activateSolidFallback = (sequence: number) => {
  if (sequence !== requestSequence) return;
  clearTransitionTimers();
  currentBgUrl.value = null;
  nextBgUrl.value = null;
  isTransitioning.value = false;
  isBlurringIn.value = false;
  useSolidFallback.value = true;
  currentDownloadUrl.value = null;
  finishInitialLoad();
};

const loadWallpaper = async (source = Number(store.coverType), temporaryId?: number) => {
  const sequence = ++requestSequence;
  wallpaperController?.abort();
  const controller = new AbortController();
  wallpaperController = controller;
  isLoading.value = true;
  store.wallpaperMaxId = activeCollection.value.count;

  let candidate: string;
  let resolvedDownloadUrl: string;
  if (source === 0) {
    candidate = resolveLocalCandidate(temporaryId);
    resolvedDownloadUrl = candidate;
  } else {
    try {
      const online = await resolveOnlineCandidate(source, controller.signal);
      if (sequence !== requestSequence) return;
      candidate = online.imageUrl;
      resolvedDownloadUrl = online.downloadUrl;
    } catch (error) {
      if (controller.signal.aborted || sequence !== requestSequence) return;
      console.error("无法获取在线壁纸，使用本地 fallback：", error);
      candidate = activeCollection.value.fallback;
      resolvedDownloadUrl = candidate;
      ElMessage({
        message: "在线壁纸加载失败，已切换到本地壁纸",
        icon: h(ErrorIcon, { theme: "filled", fill: "var(--el-message-icon-color)" }),
      });
    }
  }
  let image = await preloadImage(candidate);
  let finalUrl = candidate;

  if (!image) {
    const fallbackUrl = activeCollection.value.fallback;
    image = await preloadImage(fallbackUrl);
    finalUrl = fallbackUrl;
    resolvedDownloadUrl = fallbackUrl;
    if (source !== 0) {
      ElMessage({
        message: "在线壁纸加载失败，已切换到本地壁纸",
        icon: h(ErrorIcon, { theme: "filled", fill: "var(--el-message-icon-color)" }),
      });
    }
  }

  if (sequence !== requestSequence) return;
  if (image) {
    await commitImage(finalUrl, image, sequence, resolvedDownloadUrl);
  } else {
    ElMessage({
      message: "本地壁纸也无法加载，已使用纯色背景",
      icon: h(ErrorIcon, { theme: "filled", fill: "var(--el-message-icon-color)" }),
    });
    activateSolidFallback(sequence);
  }
  if (sequence === requestSequence) isLoading.value = false;
};

const handleCommittedImageError = () => {
  const sequence = ++requestSequence;
  activateSolidFallback(sequence);
};

const clearAutoSwitch = () => {
  if (autoSwitchTimer !== null) window.clearTimeout(autoSwitchTimer);
  autoSwitchTimer = null;
};

const scheduleAutoSwitch = () => {
  clearAutoSwitch();
  const intervals: Record<number, number> = { 0: 0, 1: 15000, 2: 30000, 3: 45000 };
  const interval = intervals[store.autoBGSwitchInterval] || 0;
  if (!interval || document.hidden) return;
  autoSwitchTimer = window.setTimeout(async () => {
    if (!isLoading.value) await loadWallpaper();
    scheduleAutoSwitch();
  }, interval);
};

const lunarNewYearRanges: Record<number, [string, string]> = {
  2026: ["2026-02-10", "2026-03-03"],
  2027: ["2027-01-30", "2027-02-20"],
  2028: ["2028-01-19", "2028-02-10"],
  2029: ["2029-02-06", "2029-02-27"],
  2030: ["2030-01-27", "2030-02-17"],
};

const automaticEffects = (date = new Date()): BackgroundEffect[] => {
  const effects: BackgroundEffect[] = [];
  const month = date.getMonth() + 1;
  const hour = date.getHours();
  if (hour >= 19 || hour < 6) effects.push("meteor");
  if ([12, 1, 2].includes(month)) effects.push("snow");
  if ([6, 7, 8].includes(month) && (hour >= 19 || hour < 6)) effects.push("firefly");
  const range = lunarNewYearRanges[date.getFullYear()];
  if (range) {
    const today = date.toISOString().slice(0, 10);
    if (today >= range[0] && today <= range[1]) effects.push("lantern");
  }
  return effects;
};

const closeAllEffects = () => {
  closeMeteor();
  closeSnowfall();
  closeFirefly();
  closeLantern();
};

const applyEffects = () => {
  if (document.hidden || reducedMotionQuery.matches || store.effectsMode === "off") {
    closeAllEffects();
    return;
  }
  const desired = new Set<BackgroundEffect>(
    store.effectsMode === "manual" ? store.selectedEffects : automaticEffects(),
  );
  desired.has("meteor") ? initMeteor() : closeMeteor();
  desired.has("snow") ? initSnowfall() : closeSnowfall();
  desired.has("firefly") ? initFirefly() : closeFirefly();
  desired.has("lantern") ? initLantern() : closeLantern();
};

const scheduleEffectRefresh = () => {
  if (effectRefreshTimer !== null) window.clearInterval(effectRefreshTimer);
  effectRefreshTimer = window.setInterval(applyEffects, 30 * 60 * 1000);
};

const handleVisibilityChange = () => {
  if (document.hidden) {
    clearAutoSwitch();
    closeAllEffects();
  } else {
    scheduleAutoSwitch();
    applyEffects();
  }
};

const handleDeviceChange = async () => {
  store.wallpaperMaxId = activeCollection.value.count;
  await loadWallpaper();
};

watch(() => store.coverType, (value) => {
  void loadWallpaper(Number(value));
  scheduleAutoSwitch();
});

watch(() => store.sBGCount, (value) => {
  if (!value || store.coverType !== 0) return;
  const temporaryId = Number(value);
  store.sBGCount = null;
  void loadWallpaper(0, temporaryId);
});

watch(() => store.wallpaperLocalId, () => {
  if (store.coverType === 0) void loadWallpaper(0);
});

watch(() => store.autoBGSwitchInterval, scheduleAutoSwitch);
watch([() => store.effectsMode, () => [...store.selectedEffects]], applyEffects);
watch(
  () => siteContent.snapshot.sectionRevisions.wallpaper,
  async () => {
    store.wallpaperMaxId = activeCollection.value.count;
    await loadWallpaper();
  },
);

onMounted(async () => {
  document.addEventListener("visibilitychange", handleVisibilityChange);
  deviceQuery.addEventListener("change", handleDeviceChange);
  reducedMotionQuery.addEventListener("change", applyEffects);
  store.wallpaperMaxId = activeCollection.value.count;
  await loadWallpaper();
  applyEffects();
  scheduleEffectRefresh();
  scheduleAutoSwitch();
});

onBeforeUnmount(() => {
  requestSequence++;
  wallpaperController?.abort();
  clearTransitionTimers();
  clearAutoSwitch();
  if (effectRefreshTimer !== null) window.clearInterval(effectRefreshTimer);
  document.removeEventListener("visibilitychange", handleVisibilityChange);
  deviceQuery.removeEventListener("change", handleDeviceChange);
  reducedMotionQuery.removeEventListener("change", applyEffects);
  closeAllEffects();
});
</script>

<style lang="scss" scoped>
.cover {
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  z-index: -1;
  overflow: hidden;
  background: linear-gradient(145deg, #243447, #101820);
  transition: 0.25s;

  &.show { z-index: 1; }

  &.solid-fallback {
    background:
      radial-gradient(circle at 25% 20%, rgb(88 124 154 / 55%), transparent 45%),
      linear-gradient(145deg, #243447, #101820);
  }

  .bg {
    position: absolute;
    inset: 0;
    width: 100%;
    height: 100%;
    object-fit: cover;
    backface-visibility: hidden;
    will-change: filter, opacity, transform;
    transition:
      filter 0.8s cubic-bezier(0.4, 0, 0.2, 1),
      opacity 0.8s cubic-bezier(0.4, 0, 0.2, 1),
      transform 0.8s cubic-bezier(0.4, 0, 0.2, 1);

    &.current {
      filter: blur(0) brightness(1);
      opacity: 1;
      transform: scale(1);

      &.blur-out {
        filter: blur(24px) brightness(0.5);
        opacity: 0;
        transform: scale(1.04);
      }
    }

    &.next {
      z-index: 2;
      filter: blur(24px) brightness(0.5);
      opacity: 0;
      transform: scale(1.04);

      &.blur-in {
        filter: blur(0) brightness(1);
        opacity: 1;
        transform: scale(1);
      }
    }
  }

  .gray {
    position: absolute;
    inset: 0;
    z-index: 3;
    opacity: 1;
    pointer-events: none;
    background-image:
      radial-gradient(rgb(0 0 0 / 0%) 0, rgb(0 0 0 / 50%) 100%),
      radial-gradient(rgb(0 0 0 / 0%) 33%, rgb(0 0 0 / 30%) 166%);
    transition: opacity 0.8s;

    &.o-hidden { opacity: 0; }
  }

  .down {
    position: absolute;
    right: 0;
    bottom: 30px;
    left: 0;
    z-index: 4;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 120px;
    height: 40px;
    margin: 0 auto;
    border-radius: 8px;
    color: white;
    background-color: rgb(0 0 0 / 30%);

    &:hover {
      transform: scale(1.05);
      background-color: rgb(0 0 0 / 60%);
    }
  }
}

@media (prefers-reduced-motion: reduce) {
  .cover,
  .cover .bg,
  .cover .gray {
    transition: none;
  }
}
</style>
