// src/components/DevSet.tsx
import { FormEvent, useMemo, useState } from "react";
import config from "@/../package.json";
import { useMainStore } from "@/store";
import { confirmAction, toast } from "@/ui/toast";
import { checkForUpdate } from "@/utils/updatecheck";
import { parseVersion } from "@/utils/ver";
import "@/components/DevSet.scss";

export default function DevSet() {
  const store = useMainStore();
  const [wallpaperId, setWallpaperId] = useState("");
  const version = useMemo(() => parseVersion(config.version), []);
  const type = ({ preview: "预览版", development: "开发版", beta: "尝鲜版", release: "正式版" } as Record<string, string>)[version.type] || "未知版本";
  const setWallpaper = (event: FormEvent) => {
    event.preventDefault();
    if (store.coverType !== 0) return toast.error("当前使用非内置壁纸，不支持该功能");
    if (!/^\d+$/.test(wallpaperId)) return toast.error("壁纸号必须为纯数字");
    if (!store.setSBGCount(Number(wallpaperId))) return toast.error(`壁纸 ID 应在 1–${store.wallpaperMaxId || 1} 之间`);
    toast.success(`已设置壁纸 ID：${wallpaperId}`); setWallpaperId("");
  };
  const reset = async () => {
    if (!await confirmAction("将恢复所有默认设置，并清除本项目的天气缓存，是否继续？")) return;
    toast.info("正在恢复默认配置，请稍后…"); await store.resetStore(); toast.success("已恢复默认设置");
  };
  const update = async () => {
    const result = await checkForUpdate(version);
    if (result.status === "true") toast.success(`当前已是最新版本：v${version.version}`);
    else if (result.status === "false") toast.info(`发现新版本 v${result.latestVersion}`);
    else toast.error("版本检测异常，请稍后再试");
  };
  return <div className="devsettings"><section><strong>壁纸调整</strong><p>使用内置壁纸时临时指定壁纸</p><form className="dev-inline" onSubmit={setWallpaper}><input value={wallpaperId} onChange={(event) => setWallpaperId(event.target.value)} inputMode="numeric" aria-label="壁纸 ID" /><button type="submit" disabled={!wallpaperId}>确定</button></form></section><section><strong>个性化设置</strong><label className="dev-check"><input type="checkbox" checked={store.msgNameShow} onChange={(event) => store.patch({ msgNameShow: event.target.checked })} />信息区域显示自定义名</label></section><section><strong>维护</strong><div className="dev-actions"><button type="button" onClick={() => void reset()}>重置所有设置</button><button type="button" onClick={() => void update()}>检查更新</button></div><p>版本号 v{version.version}，{type}，{version.channel} 渠道，by {version.upa}。</p></section></div>;
}

// src/components/DevSet.vue
<template>
    <div class="devsettings">
        <el-collapse class="collapse" v-model="activeName" accordion>
            <el-collapse-item title="壁纸调整" name="2">
                <div class="item">
                    <div class="upver">使用内置壁纸时临时指定壁纸</div>
                </div>
                <div class="item">
                    <el-form :model="form" style="max-width: 120px" label-width="auto"
                        @submit.prevent="handleSetWallpaper">
                        <el-form-item prop="wallpaperId" :rules="[
                            { required: true, message: '壁纸号不能为空', trigger: 'blur' },
                            { pattern: /^\d+$/, message: '壁纸号必须为纯数字', trigger: ['blur', 'change'] }
                        ]">
                            <el-input v-model="form.wallpaperId" type="text" autocomplete="off" clearable />
                            <el-button plain class="el-button" native-type="submit"
                                :disabled="!form.wallpaperId">确定</el-button>
                        </el-form-item>
                    </el-form>
                </div>
            </el-collapse-item>
            <el-collapse-item title="个性化设置" name="3">
                <div class="item">
                    <span class="text">信息区域显示自定义名</span>
                    <el-switch v-model="msgNameShow" inline-prompt :active-icon="CheckSmall"
                        :inactive-icon="CloseSmall" />
                </div>
            </el-collapse-item>
            <el-collapse-item title="重置" name="5">
                <div class="item">
                    <el-button plain class="el-button" @click="resetSettings()">重置所有设置</el-button>
                </div>
            </el-collapse-item>
            <el-collapse-item title="检查版本更新" name="6">
                <div class="item">
                    <div class="upver">版本号 v{{ versionInfo.version }}，{{ versTypeT }}，{{ versionInfo.channel }} 渠道，by {{
                        versionInfo.upa }} 。
                    </div>
                </div>
                <div class="item">
                    <el-button plain class="el-button" @click="checkUpdate()">检查更新</el-button>
                </div>
            </el-collapse-item>
        </el-collapse>
    </div>
</template>

<script setup lang="ts">
import { ref, reactive } from 'vue'
import { CheckSmall, CloseSmall } from "@icon-park/vue-next";
import { mainStore } from "@/store";
import { storeToRefs } from "pinia";
import { parseVersion } from "@/utils/ver";
import { checkForUpdate } from "@/utils/updatecheck";
import config from "@/../package.json";
const activeName = ref("0");
const store = mainStore();
const {
    msgNameShow
} = storeToRefs(store);

const versionInfo = parseVersion(config.version);
const versTypeT = computed(() => {
    switch (versionInfo.type) {
        case 'preview':
            return '预览版';
        case 'development':
            return '开发版';
        case 'beta':
            return '尝鲜版';
        case 'release':
            return '正式版';
        default:
            return '未知版本';
    };
});

const checkUpdate = async () => {
    const updinfo = await checkForUpdate(versionInfo);
    if (updinfo.status == 'true') {
        ElMessage({
            message: `当前已是最新版本！ v${versionInfo.version} ， ${versionInfo.type} 。`,
            grouping: true,
        });
    } else if (updinfo.status == 'false') {
        ElMessage({
            message: `发现新版本 v${updinfo.latestVersion}，${updinfo.isPreview == 'true' ? "预览版" : "正式版"}，${updinfo.versionType} ，快来体验吧！`,
            grouping: true,
        });
    } else {
        ElMessage({
            message: `版本检测异常，稍后再试试叭~`,
            grouping: true,
        });
    };
};

const form = reactive({
    wallpaperId: ''
})

const resetSettings = async () => {
    try {
        await ElMessageBox.confirm(
            '将恢复所有默认设置，并清除本项目的天气缓存，是否继续？',
            '重置设置',
            {
                confirmButtonText: '重置',
                cancelButtonText: '取消',
                type: 'warning',
            },
        );
        ElMessage({
            dangerouslyUseHTMLString: true,
            message: `正在恢复默认配置，请稍后...`,
        });
        await store.resetStore();
        ElMessage.success('已恢复默认设置');
    } catch {
        // 用户取消重置。
    }
};

const handleSetWallpaper = () => {
    if (store.coverType != 0) {
        ElMessage.error('当前使用非内置壁纸，不支持该功能！');
        return;
    };
    if (!form.wallpaperId.trim()) {
        ElMessage.error('壁纸号不能为空！');
        return;
    };
    if (!/^\d+$/.test(form.wallpaperId)) {
        ElMessage.error('壁纸号必须为纯数字！');
        return;
    };
    const wallpaperId = parseInt(form.wallpaperId, 10);
    if (!store.setSBGCount(wallpaperId)) {
        ElMessage.error(`壁纸 ID 应在 1–${store.wallpaperMaxId || 1} 之间`);
        return;
    }
    ElMessage.success(`已设置壁纸ID: ${wallpaperId}`);
    form.wallpaperId = '';
};
</script>

<style lang="scss" scoped>
.devsettings {
    .text {
        color: var(--text-color);
    }

    .collapse {
        border-radius: 8px;
        --el-collapse-content-bg-color: var(--set-coll-background-ck-color);
        border-color: transparent;
        overflow: hidden;

        :deep(.el-collapse-item__header) {
            background-color: var(--set-coll-background-color);
            color: var(--text-color);
            font-size: 15px;
            padding-left: 15px;
            border-color: transparent;
        }

        :deep(.el-collapse-item__wrap) {
            border-color: transparent;

            .el-collapse-item__content {
                padding: 18px;

                .item {
                    display: flex;
                    align-items: center;
                    justify-content: space-between;
                    flex-wrap: wrap;
                    font-size: 14px;

                    .el-switch__core {
                        border-color: transparent;
                        background-color: var(--set-radio-bg-ck-color);
                    }

                    .el-button {
                        margin: 8px 12px;
                        border: 2px solid transparent;
                        border-radius: 6px;
                        border-color: transparent;
                        background-color: var(--set-radio-bg-ck-color);
                        transition: all 0.1s ease;
                        position: relative;
                        overflow: hidden;
                        transform: scale(1);
                        color: var(--text-color);
                    }

                    .el-button.active {
                        border-color: transparent;
                        background-color: var(--set-radio-bg-ck-color);
                        border: 2px solid var(--set-radio-border-color) !important;
                        transition: all 0.1s ease;
                        position: relative;
                        overflow: hidden;
                        transform: scale(1);
                        color: var(--text-color);
                    }

                    .el-button:active {
                        transform: scale(0.9);
                        color: var(--text-color);
                        border: 1.5px solid rgba(176, 224, 230, 1) !important;
                    }

                    .el-radio-group {
                        .el-radio {
                            margin: 2px 10px 2px 0;
                            border-radius: 5px;

                            &:last-child {
                                margin-right: 0;
                            }
                        }
                    }

                    .el-input {
                        border-color: transparent;
                        background-color: #ffffff30;
                    }

                    .upver {
                        font-size: 0.75rem;
                        font-family: MiSans VF;
                        color: var(--text-color);
                    }
                }

                .el-radio-group {
                    justify-content: space-between;

                    .el-radio {
                        margin: 10px 16px;
                        background: var(--set-radio-bg-color);
                        border: 2px solid transparent;
                        border-radius: 8px;

                        .el-radio__label {
                            color: var(--text-color);
                        }

                        .el-radio__inner {
                            background: var(--set-radio-bg-color) !important;
                            border: 2px solid var(--set-radio-border-color) !important;
                        }

                        &.is-checked {
                            background: var(--set-radio-bg-ck-color) !important;
                            border: 2px solid var(--set-radio-border-color) !important;
                        }

                        .is-checked {
                            .el-radio__inner {
                                background-color: var(--set-radio-bg-ck-color) !important;
                                border-color: var(--set-radio-border-ck-color) !important;
                            }

                            &+.el-radio__label {
                                color: var(--text-color) !important;
                            }
                        }
                    }
                }
            }
        }
    }
}
</style>
