// src/components/PlayerSeekBar.vue
<template>
  <div class="player-seek" :class="{ 'with-time': showTime }">
    <span v-if="showTime" class="time current-time">{{ formatTime(displayedTime) }}</span>
    <div
      ref="track"
      class="seek-track"
      :class="{ dragging: isDragging, disabled: !safeDuration }"
      role="slider"
      :tabindex="safeDuration ? 0 : -1"
      :aria-label="label"
      :aria-disabled="!safeDuration"
      aria-valuemin="0"
      :aria-valuemax="safeDuration"
      :aria-valuenow="Math.round(displayedTime)"
      :aria-valuetext="`${formatTime(displayedTime)} / ${formatTime(safeDuration)}`"
      @pointerdown="handlePointerDown"
      @pointermove="handlePointerMove"
      @pointerup="handlePointerUp"
      @pointercancel="handlePointerCancel"
      @keydown="handleKeydown"
    >
      <div class="seek-runway">
        <div class="seek-progress" :style="{ width: `${displayedProgress}%` }" />
        <span class="seek-thumb" :style="{ left: `${displayedProgress}%` }" aria-hidden="true" />
        <span
          v-if="loading"
          class="seek-loading"
          :style="{ left: `${loadingPosition}%` }"
          aria-hidden="true"
        />
      </div>
    </div>
    <span v-if="showTime" class="time duration-time">{{ formatTime(safeDuration) }}</span>
  </div>
</template>

<script setup lang="ts">
const props = withDefaults(
  defineProps<{
    currentTime: number;
    duration: number;
    loading?: boolean;
    showTime?: boolean;
    label?: string;
  }>(),
  {
    loading: false,
    showTime: false,
    label: "播放进度",
  },
);

const emit = defineEmits<{
  seek: [time: number];
}>();

const track = ref<HTMLElement | null>(null);
const isDragging = ref(false);
const activePointerId = ref<number | null>(null);
const previewTime = ref(0);

const safeDuration = computed(() =>
  Number.isFinite(props.duration) && props.duration > 0 ? props.duration : 0,
);

const safeCurrentTime = computed(() =>
  safeDuration.value ? Math.min(safeDuration.value, Math.max(0, props.currentTime)) : 0,
);

const displayedTime = computed(() =>
  isDragging.value ? previewTime.value : safeCurrentTime.value,
);
const displayedProgress = computed(() =>
  safeDuration.value ? (displayedTime.value / safeDuration.value) * 100 : 0,
);
const loadingPosition = computed(() => Math.min(99, Math.max(1, displayedProgress.value)));

const formatTime = (seconds: number) => {
  const safeSeconds = Math.max(0, Math.floor(seconds));
  const minutes = Math.floor(safeSeconds / 60);
  const remainder = safeSeconds % 60;
  return `${minutes}:${remainder.toString().padStart(2, "0")}`;
};

const setPreviewFromClientX = (clientX: number) => {
  if (!track.value || !safeDuration.value) return;
  const rect = track.value.getBoundingClientRect();
  if (rect.width <= 0) return;
  const ratio = Math.min(1, Math.max(0, (clientX - rect.left) / rect.width));
  previewTime.value = ratio * safeDuration.value;
};

const commitTime = (time: number) => {
  if (!safeDuration.value) return;
  emit("seek", Math.min(safeDuration.value, Math.max(0, time)));
};

const handlePointerDown = (event: PointerEvent) => {
  if (!safeDuration.value || (event.pointerType === "mouse" && event.button !== 0)) return;
  event.preventDefault();
  activePointerId.value = event.pointerId;
  isDragging.value = true;
  setPreviewFromClientX(event.clientX);
  track.value?.setPointerCapture(event.pointerId);
};

const handlePointerMove = (event: PointerEvent) => {
  if (!isDragging.value || activePointerId.value !== event.pointerId) return;
  event.preventDefault();
  setPreviewFromClientX(event.clientX);
};

const finishPointer = (event: PointerEvent, commit: boolean) => {
  if (!isDragging.value || activePointerId.value !== event.pointerId) return;
  if (commit) {
    setPreviewFromClientX(event.clientX);
    commitTime(previewTime.value);
  } else {
    previewTime.value = safeCurrentTime.value;
  }
  if (track.value?.hasPointerCapture(event.pointerId)) {
    track.value.releasePointerCapture(event.pointerId);
  }
  activePointerId.value = null;
  isDragging.value = false;
};

const handlePointerUp = (event: PointerEvent) => finishPointer(event, true);
const handlePointerCancel = (event: PointerEvent) => finishPointer(event, false);

const handleKeydown = (event: KeyboardEvent) => {
  if (!safeDuration.value) return;
  let nextTime: number | null = null;
  switch (event.key) {
    case "ArrowLeft":
    case "ArrowDown":
      nextTime = safeCurrentTime.value - 5;
      break;
    case "ArrowRight":
    case "ArrowUp":
      nextTime = safeCurrentTime.value + 5;
      break;
    case "Home":
      nextTime = 0;
      break;
    case "End":
      nextTime = safeDuration.value;
      break;
  }
  if (nextTime === null) return;
  event.preventDefault();
  commitTime(nextTime);
};
</script>

<style lang="scss" scoped>
.player-seek {
  width: 100%;
  min-width: 0;
  display: flex;
  align-items: center;
  gap: 10px;

  .time {
    flex: 0 0 auto;
    min-width: 38px;
    color: rgba(from var(--text-color) r g b / 0.7);
    font-size: 0.72rem;
    font-variant-numeric: tabular-nums;
  }

  .duration-time {
    text-align: right;
  }
}

.seek-track {
  position: relative;
  width: 100%;
  height: 22px;
  flex: 1 1 auto;
  cursor: pointer;
  touch-action: none;
  user-select: none;

  &.disabled {
    cursor: default;
    opacity: 0.55;
  }

  &:focus-visible {
    outline: none;

    .seek-runway {
      box-shadow: 0 0 0 2px rgba(from var(--player-slider-main-color) r g b / 0.28);
    }
  }
}

.seek-runway {
  position: absolute;
  top: 50%;
  left: 0;
  width: 100%;
  height: 4px;
  overflow: visible;
  border-radius: 999px;
  background: var(--player-slider-runway-color);
  transform: translateY(-50%);
}

.seek-progress {
  height: 100%;
  border-radius: inherit;
  background: var(--player-slider-main-color);
  transition: width 0.15s linear;
}

.seek-thumb {
  position: absolute;
  top: 50%;
  width: 12px;
  height: 12px;
  border: 2px solid rgba(from var(--background-color) r g b / 0.88);
  border-radius: 50%;
  background: var(--player-slider-main-color);
  opacity: 0;
  transform: translate(-50%, -50%) scale(0.75);
  transition:
    opacity 0.15s ease,
    transform 0.15s ease;
  pointer-events: none;
}

.seek-loading {
  position: absolute;
  top: 50%;
  width: 8px;
  height: 8px;
  border: 2px solid rgba(from var(--text-color) r g b / 0.35);
  border-top-color: var(--text-color);
  border-radius: 50%;
  transform: translate(-50%, -50%);
  animation: seek-loading-spin 0.8s linear infinite;
}

.seek-track:hover .seek-thumb,
.seek-track:focus-visible .seek-thumb,
.seek-track.dragging .seek-thumb {
  opacity: 1;
  transform: translate(-50%, -50%) scale(1);
}

.seek-track.dragging .seek-progress {
  transition: none;
}

@keyframes seek-loading-spin {
  to {
    transform: translate(-50%, -50%) rotate(360deg);
  }
}

@media (prefers-reduced-motion: reduce) {
  .seek-progress,
  .seek-thumb {
    transition: none;
  }

  .seek-loading {
    animation: none;
  }
}
</style>

// src/components/PlayerSeekBar.tsx
import { useMemo, useRef, useState } from "react";
import type { KeyboardEvent, PointerEvent } from "react";
import "@/components/PlayerSeekBar.scss";

interface Props {
  currentTime: number;
  duration: number;
  loading?: boolean;
  showTime?: boolean;
  label?: string;
  className?: string;
  onSeek: (time: number) => void;
}

const formatTime = (seconds: number) => {
  const safe = Math.max(0, Math.floor(seconds));
  return `${Math.floor(safe / 60)}:${(safe % 60).toString().padStart(2, "0")}`;
};

export default function PlayerSeekBar({ currentTime, duration, loading = false, showTime = false, label = "播放进度", className = "", onSeek }: Props) {
  const track = useRef<HTMLDivElement>(null);
  const pointer = useRef<number | null>(null);
  const [dragging, setDragging] = useState(false);
  const [preview, setPreview] = useState(0);
  const safeDuration = Number.isFinite(duration) && duration > 0 ? duration : 0;
  const safeTime = safeDuration ? Math.min(safeDuration, Math.max(0, currentTime)) : 0;
  const displayed = dragging ? preview : safeTime;
  const progress = safeDuration ? displayed / safeDuration * 100 : 0;
  const ariaText = useMemo(() => `${formatTime(displayed)} / ${formatTime(safeDuration)}`, [displayed, safeDuration]);
  const fromX = (clientX: number) => {
    const rect = track.current?.getBoundingClientRect();
    if (!rect || rect.width <= 0 || !safeDuration) return preview;
    return Math.min(1, Math.max(0, (clientX - rect.left) / rect.width)) * safeDuration;
  };
  const down = (event: PointerEvent<HTMLDivElement>) => {
    if (!safeDuration || (event.pointerType === "mouse" && event.button !== 0)) return;
    event.preventDefault(); pointer.current = event.pointerId; setDragging(true); setPreview(fromX(event.clientX));
    track.current?.setPointerCapture(event.pointerId);
  };
  const move = (event: PointerEvent<HTMLDivElement>) => {
    if (!dragging || pointer.current !== event.pointerId) return;
    event.preventDefault(); setPreview(fromX(event.clientX));
  };
  const finish = (event: PointerEvent<HTMLDivElement>, commit: boolean) => {
    if (!dragging || pointer.current !== event.pointerId) return;
    const next = fromX(event.clientX);
    if (commit) onSeek(next); else setPreview(safeTime);
    if (track.current?.hasPointerCapture(event.pointerId)) track.current.releasePointerCapture(event.pointerId);
    pointer.current = null; setDragging(false);
  };
  const keydown = (event: KeyboardEvent<HTMLDivElement>) => {
    const values: Record<string, number> = { ArrowLeft: safeTime - 5, ArrowDown: safeTime - 5, ArrowRight: safeTime + 5, ArrowUp: safeTime + 5, Home: 0, End: safeDuration };
    if (!safeDuration || !(event.key in values)) return;
    event.preventDefault(); onSeek(Math.min(safeDuration, Math.max(0, values[event.key]!)));
  };
  return <div className={`player-seek${showTime ? " with-time" : ""}${className ? ` ${className}` : ""}`}>
    {showTime && <span className="time current-time">{formatTime(displayed)}</span>}
    <div ref={track} className={`seek-track${dragging ? " dragging" : ""}${safeDuration ? "" : " disabled"}`} role="slider" tabIndex={safeDuration ? 0 : -1} aria-label={label} aria-disabled={!safeDuration} aria-valuemin={0} aria-valuemax={safeDuration} aria-valuenow={Math.round(displayed)} aria-valuetext={ariaText} onPointerDown={down} onPointerMove={move} onPointerUp={(event) => finish(event, true)} onPointerCancel={(event) => finish(event, false)} onKeyDown={keydown}>
      <div className="seek-runway"><div className="seek-progress" style={{ width: `${progress}%` }} /><span className="seek-thumb" style={{ left: `${progress}%` }} aria-hidden="true" />{loading && <span className="seek-loading" style={{ left: `${Math.min(99, Math.max(1, progress))}%` }} aria-hidden="true" />}</div>
    </div>
    {showTime && <span className="time duration-time">{formatTime(safeDuration)}</span>}
  </div>;
}
