// src/components/Set.tsx
import { useState } from "react";
import DevSet from "@/components/DevSet";
import { useMainStore } from "@/store";
import type { BackgroundEffect, BackgroundEffectMode, MainState } from "@/typings/store";
import { toast } from "@/ui/toast";
import "@/components/Set.scss";

const RadioSet = <Value extends string | number>({ value, values, onChange, name }: { value: Value; values: Array<[Value, string]>; onChange: (value: Value) => void; name: string }) => <div className="choice-group">{values.map(([item, label]) => <label key={String(item)} className={value === item ? "is-selected" : ""}><input type="radio" name={name} checked={value === item} onChange={() => onChange(item)} />{label}</label>)}</div>;
const Toggle = ({ checked, onChange, label }: { checked: boolean; onChange: (value: boolean) => void; label: string }) => <button type="button" className={`native-switch${checked ? " is-on" : ""}`} role="switch" aria-checked={checked} aria-label={label} onClick={() => onChange(!checked)}><span /></button>;

export default function Set() {
  const state = useMainStore();
  const [wallpaperId, setWallpaperId] = useState(state.wallpaperLocalId?.toString() || "");
  const set = <Key extends keyof MainState>(key: Key, value: MainState[Key]) => state.setSetting(key, value);
  const updateEffect = (effect: BackgroundEffect, checked: boolean) => set("selectedEffects", checked ? [...state.selectedEffects, effect] : state.selectedEffects.filter((item) => item !== effect));
  const applyWallpaper = () => {
    if (!wallpaperId.trim()) return clearWallpaper();
    if (!state.setWallpaperLocalId(wallpaperId)) return toast.error(`壁纸 ID 应在 1–${state.wallpaperMaxId || 1} 之间`);
    toast.success(`默认壁纸已设置为 ${state.wallpaperLocalId}`);
  };
  const clearWallpaper = () => { state.setWallpaperLocalId(null); setWallpaperId(""); toast.success("默认壁纸已改为随机"); };
  return <div className="setting"><div className="native-collapse"><details open><summary>个性壁纸</summary><div className="collapse-content"><RadioSet name="wallpaper" value={state.coverType} values={[[0, "默认壁纸"], [1, "每日一图"], [2, "随机风景"], [3, "随机动漫"]]} onChange={(value) => { set("coverType", value); toast.success("壁纸更换成功"); }} /><div className="item"><span className="text">自动切换</span><RadioSet name="auto-wallpaper" value={state.autoBGSwitchInterval} values={[[0, "关闭"], [1, "15 秒"], [2, "30 秒"], [3, "45 秒"]]} onChange={(value) => set("autoBGSwitchInterval", value)} /></div>{state.coverType === 0 && <div className="item"><span className="text">默认壁纸 ID</span><div className="inline-control"><input value={wallpaperId} onChange={(event) => setWallpaperId(event.target.value)} type="number" min="1" max={state.wallpaperMaxId || undefined} placeholder="随机" /><button type="button" onClick={applyWallpaper}>应用</button><button type="button" onClick={clearWallpaper}>随机</button></div></div>}</div></details><details><summary>个性化调整</summary><div className="collapse-content"><div className="item"><span className="text">建站日期显示</span><Toggle label="建站日期显示" checked={state.siteStartShow} onChange={(value) => set("siteStartShow", value)} /></div><div className="item effect-settings"><span className="text">背景特效</span><RadioSet name="effects-mode" value={state.effectsMode} values={[["auto", "自动"], ["off", "关闭"], ["manual", "手动"]] as Array<[BackgroundEffectMode, string]>} onChange={(value) => set("effectsMode", value)} /></div>{state.effectsMode === "manual" && <div className="item effect-settings"><span className="text">手动选择</span><div className="checkbox-group">{([['snow', '雪'], ['firefly', '萤火虫'], ['lantern', '灯笼'], ['meteor', '流星']] as Array<[BackgroundEffect, string]>).map(([effect, label]) => <label key={effect}><input type="checkbox" checked={state.selectedEffects.includes(effect)} onChange={(event) => updateEffect(effect, event.target.checked)} />{label}</label>)}</div></div>}<div className="item"><span className="text">底栏背景模糊</span><Toggle label="底栏背景模糊" checked={state.footerBlur} onChange={(value) => set("footerBlur", value)} /></div></div></details><details><summary>其他设置</summary><div className="collapse-content"><div className="text">暂时没有其它啦 qwq</div></div></details>{state.setV && <details><summary>开发设置</summary><div className="collapse-content"><DevSet /></div></details>}</div></div>;
}

// src/components/Set.vue
<template>
  <div class="setting">
    <el-collapse class="collapse" v-model="activeName" accordion>
      <el-collapse-item title="个性壁纸" name="1">
        <div class="bg-set">
          <el-radio-group v-model="coverType" text-color="#ffffff" @change="radioChange">
            <el-radio :value="0" size="large" border>默认壁纸</el-radio>
            <el-radio :value="1" size="large" border>每日一图</el-radio>
            <el-radio :value="2" size="large" border>随机风景</el-radio>
            <el-radio :value="3" size="large" border>随机动漫</el-radio>
          </el-radio-group>
        </div>
        <div class="item">
          <span class="text">自动切换</span>
          <el-radio-group v-model="autoBGSwitchInterval" size="small" text-color="#FFFFFF">
            <el-radio :value="0" border>关闭</el-radio>
            <el-radio :value="1" border>15 秒</el-radio>
            <el-radio :value="2" border>30 秒</el-radio>
            <el-radio :value="3" border>45 秒</el-radio>
          </el-radio-group>
        </div>
        <div v-if="coverType === 0" class="item">
          <span class="text">默认壁纸 ID</span>
          <div class="inline-control">
            <input v-model="wallpaperIdInput" type="number" min="1" :max="store.wallpaperMaxId || undefined"
              inputmode="numeric" aria-label="默认壁纸 ID" placeholder="随机" />
            <button type="button" @click="applyDefaultWallpaper">应用</button>
            <button type="button" @click="clearDefaultWallpaper">随机</button>
          </div>
        </div>
      </el-collapse-item>
      <el-collapse-item title="个性化调整" name="3">
        <div class="item">
          <span class="text">建站日期显示</span>
          <el-switch v-model="siteStartShow" inline-prompt :active-icon="CheckSmall" :inactive-icon="CloseSmall" />
        </div>
        <div class="item effect-settings">
          <span class="text">背景特效</span>
          <el-radio-group v-model="effectsMode" size="small" text-color="#FFFFFF">
            <el-radio value="auto" border>自动</el-radio>
            <el-radio value="off" border>关闭</el-radio>
            <el-radio value="manual" border>手动</el-radio>
          </el-radio-group>
        </div>
        <div v-if="effectsMode === 'manual'" class="item effect-settings">
          <span class="text">手动选择</span>
          <el-checkbox-group v-model="selectedEffects">
            <el-checkbox value="snow">雪</el-checkbox>
            <el-checkbox value="firefly">萤火虫</el-checkbox>
            <el-checkbox value="lantern">灯笼</el-checkbox>
            <el-checkbox value="meteor">流星</el-checkbox>
          </el-checkbox-group>
        </div>
        <div class="item">
          <span class="text">底栏背景模糊</span>
          <el-switch v-model="footerBlur" inline-prompt :active-icon="CheckSmall" :inactive-icon="CloseSmall" />
        </div>
        <div class="item">
          <span class="text">显示底栏音乐进度条</span>
          <el-switch v-model="footerProgressBar" inline-prompt :active-icon="CheckSmall" :inactive-icon="CloseSmall" />
        </div>
      </el-collapse-item>
      <el-collapse-item title="歌词设置" name="5">
        <div class="item">
          <span class="text">显示底栏歌词</span>
          <el-switch v-model="playerLrcShow" inline-prompt :active-icon="CheckSmall" :inactive-icon="CloseSmall" />
        </div>
        <div v-if="playerLrcShow" class="item">
          <span class="text">逐字歌词解析总开关</span>
          <el-switch v-model="playerDWRCShow" inline-prompt :active-icon="CheckSmall" :inactive-icon="CloseSmall" />
        </div>
        <div v-if="playerLrcShow && playerDWRCShow" class="item">
          <span class="text">逐字效果增强开关</span>
          <el-switch v-model="playerDWRCShowPro" inline-prompt :active-icon="CheckSmall" :inactive-icon="CloseSmall" />
        </div>
        <div class="item">
          <span class="text">移除逐字歌词中的元数据</span>
          <el-switch v-model="playerRMMetadata" inline-prompt :active-icon="CheckSmall" :inactive-icon="CloseSmall" />
        </div>
        <div class="item">
          <span class="text">逐行歌词翻译显示开关</span>
          <el-switch v-model="playerTrLrc" inline-prompt :active-icon="CheckSmall" :inactive-icon="CloseSmall" />
        </div>
      </el-collapse-item>
      <el-collapse-item title="其他设置" name="6">
        <div class="text">暂时没有其它啦qwq</div>
      </el-collapse-item>
      <el-collapse-item v-if="setV" title="开发设置" name="8">
        <DevSet />
      </el-collapse-item>
    </el-collapse>
  </div>
</template>

<script setup lang="ts">
import { CheckSmall, CloseSmall, SuccessPicture } from "@icon-park/vue-next";
import DevSet from "@/components/DevSet.vue";
import { mainStore } from "@/store";
import { storeToRefs } from "pinia";

const store = mainStore();
const {
  coverType,
  siteStartShow,
  playerLrcShow,
  footerBlur,
  playerTrLrc,
  playerDWRCShow,
  playerDWRCShowPro,
  playerRMMetadata,
  footerProgressBar,
  autoBGSwitchInterval,
  effectsMode,
  selectedEffects,
  setV,
} = storeToRefs(store);

// 默认选中项
const activeName = ref("0");
const wallpaperIdInput = ref(store.wallpaperLocalId?.toString() || "");

// 壁纸切换
const radioChange = () => {
  ElMessage({
    message: "壁纸更换成功",
    icon: h(SuccessPicture, {
      theme: "filled",
      fill: "var(--el-message-icon-color)",
    }),
  });
};

const applyDefaultWallpaper = () => {
  if (!wallpaperIdInput.value.trim()) {
    clearDefaultWallpaper();
    return;
  }
  if (!store.setWallpaperLocalId(wallpaperIdInput.value)) {
    ElMessage.error(`壁纸 ID 应在 1–${store.wallpaperMaxId || 1} 之间`);
    return;
  }
  ElMessage.success(`默认壁纸已设置为 ${store.wallpaperLocalId}`);
};

const clearDefaultWallpaper = () => {
  store.setWallpaperLocalId(null);
  wallpaperIdInput.value = "";
  ElMessage.success("默认壁纸已改为随机");
};
</script>

<style lang="scss" scoped>
.setting {
  .text {
    color: var(--text-color);
  }

  .collapse {
    border-radius: 8px;
    --el-collapse-content-bg-color: var(--set-coll-background-ck-color);
    border-color: transparent;
    overflow: hidden;

    :deep(.el-collapse-item__header) {
      background-color: var(--set-coll-background-color);
      color: var(--text-color);
      font-size: 15px;
      padding-left: 18px;
      border-color: transparent;
    }

    :deep(.el-collapse-item__wrap) {
      border-color: transparent;

      .el-collapse-item__content {
        padding: 20px;

        .item {
          display: flex;
          align-items: center;
          justify-content: space-between;
          flex-wrap: wrap;
          font-size: 14px;

          .inline-control {
            display: flex;
            gap: 8px;
            align-items: center;

            input,
            button {
              min-height: 32px;
              border: 1px solid var(--set-radio-border-color);
              border-radius: 6px;
              color: var(--text-color);
              background: var(--set-radio-bg-color);
            }

            input {
              width: 76px;
              padding: 0 8px;
            }

            button {
              padding: 0 10px;
              cursor: pointer;
            }
          }

          &.effect-settings {
            gap: 12px;
          }

          .el-switch__core {
            border-color: transparent;
            background-color: var(--set-radio-bg-ck-color);
          }

          .el-radio-group {
            .el-radio {
              margin: 2px 10px 2px 0;
              border-radius: 5px;

              &:last-child {
                margin-right: 0;
              }
            }
          }
        }

        .el-radio-group {
          justify-content: space-between;

          .el-radio {
            margin: 10px 16px;
            background: var(--set-radio-bg-color);
            border: 2px solid transparent;
            border-radius: 8px;

            .el-radio__label {
              color: var(--text-color);
            }

            .el-radio__inner {
              background: var(--set-radio-bg-color) !important;
              border: 2px solid var(--set-radio-border-color) !important;
            }

            &.is-checked {
              background: var(--set-radio-bg-color) !important;
              border: 2px solid var(--set-radio-border-color) !important;
            }

            .is-checked {
              .el-radio__inner {
                background-color: var(--set-radio-bg-ck-color) !important;
                border-color: var(--set-radio-border-ck-color) !important;
              }

              &+.el-radio__label {
                color: var(--text-color) !important;
              }
            }
          }
        }
      }
    }
  }
}
</style>
