// src/components/TimeCapsule.vue
<template>
  <div class="time-capsule">
    <div class="title">
      <hourglass-full theme="two-tone" size="24" :fill="['var(--time-icon-one-color)', 'var(--time-icon-two-color)']" />
      <span>时光胶囊</span>
    </div>
    <div v-if="timeData" class="all-capsule">
      <div v-for="(item, tag, index) in timeData" :key="index" class="capsule-item">
        <div class="item-title">
          <span class="percentage">
            {{ item.name }}已度过
            <strong>{{ item.passed }}</strong>
            {{ tag === "day" ? "小时" : "天" }}
          </span>
          <span class="remaining">
            剩余&nbsp;{{ item.remaining }}&nbsp;{{ tag === "day" ? "小时" : "天" }}
          </span>
        </div>
        <el-progress :text-inside="true" :stroke-width="20" :percentage="Number(item.percentage)" />
      </div>
      <!-- 建站日期 -->
      <div v-if="store.siteStartShow" class="capsule-item start">
        <div class="item-title">{{ startDateText }}</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { HourglassFull } from "@icon-park/vue-next";
import { getTimeCapsule, siteDateStatistics } from "@/utils/getTime.js";
import { mainStore } from "@/store";
import { useSiteContentStore } from "@/stores/siteContent";
import { onMounted, onBeforeUnmount, ref } from "vue";
const store = mainStore();
const siteContent = useSiteContentStore();

// 进度条数据
const timeData = ref(getTimeCapsule());
const startDate = computed(() => siteContent.profile.startDate);
const startDateText = ref<string | null>(null);
const timeInterval = ref<number | null>(null);

onMounted(() => {
  timeInterval.value = window.setInterval(() => {
    timeData.value = getTimeCapsule();
    if (startDate.value) startDateText.value = siteDateStatistics(new Date(startDate.value));
  }, 1000);
});

onBeforeUnmount(() => {
  if (timeInterval.value !== null) {
    clearInterval(timeInterval.value);
    timeInterval.value = null;
  }
});
</script>

<style lang="scss" scoped>
.time-capsule {
  width: 100%;

  .title {
    display: flex;
    flex-direction: row;
    align-items: center;
    margin: 0.2rem 0 1.5rem;
    font-size: 1.1rem;

    .i-icon {
      display: flex;
      justify-content: center;
      align-items: center;
      margin-right: 6px;
    }
  }

  .all-capsule {
    .capsule-item {
      margin-bottom: 1rem;

      .item-title {
        display: flex;
        flex-direction: row;
        align-items: center;
        justify-content: space-between;
        margin: 1rem 0rem 0.5rem 0rem;
        font-size: 0.95rem;

        .remaining {
          opacity: 0.6;
          font-size: 0.85rem;
          font-style: oblique;
        }
      }

      &:last-child {
        margin-bottom: 0;
      }

      &.start {
        .item-title {
          justify-content: center;
          opacity: 0.8;
          font-size: 0.85rem;
        }
      }
    }
  }
}
</style>

// src/components/TimeCapsule.tsx
import { useEffect, useState } from "react";
import { HourglassFull } from "@icon-park/react";
import { getTimeCapsule, siteDateStatistics } from "@/utils/getTime";
import { useMainStore } from "@/store";
import { useSiteContentStore } from "@/stores/siteContent";
import "@/components/TimeCapsule.scss";

export default function TimeCapsule() {
  const showStart = useMainStore((state) => state.siteStartShow);
  const startDate = useSiteContentStore((state) => state.snapshot.sections.profile.startDate);
  const [timeData, setTimeData] = useState(getTimeCapsule());
  const [startText, setStartText] = useState(() => startDate ? siteDateStatistics(new Date(startDate)) : "");
  useEffect(() => {
    const update = () => {
      setTimeData(getTimeCapsule());
      setStartText(startDate ? siteDateStatistics(new Date(startDate)) : "");
    };
    update();
    const timer = window.setInterval(update, 1000);
    return () => window.clearInterval(timer);
  }, [startDate]);
  return (
    <div className="time-capsule">
      <div className="title"><HourglassFull theme="two-tone" size="24" fill={["var(--time-icon-one-color)", "var(--time-icon-two-color)"]} /><span>时光胶囊</span></div>
      <div className="all-capsule">
        {Object.entries(timeData).map(([tag, item]) => (
          <div key={tag} className="capsule-item">
            <div className="item-title">
              <span className="percentage">{item.name}已度过 <strong>{item.passed}</strong> {tag === "day" ? "小时" : "天"}</span>
              <span className="remaining">剩余&nbsp;{item.remaining}&nbsp;{tag === "day" ? "小时" : "天"}</span>
            </div>
            <div className="time-progress"><span style={{ width: `${item.percentage}%` }}>{item.percentage}%</span></div>
          </div>
        ))}
        {showStart && startText && <div className="capsule-item start"><div className="item-title">{startText}</div></div>}
      </div>
    </div>
  );
}
