// src/components/VolumeSlider.tsx
import { useEffect, useRef } from "react";
import type { KeyboardEvent, PointerEvent } from "react";
import "@/components/VolumeSlider.scss";

interface Props { value: number; onPreview: (value: number) => void; onCommit: (value: number) => void }
const normalize = (value: number) => Math.min(1, Math.max(0, value));

export default function VolumeSlider({ value, onPreview, onCommit }: Props) {
  const track = useRef<HTMLDivElement>(null);
  const percentText = useRef<HTMLSpanElement>(null);
  const current = useRef(normalize(value));
  const pointer = useRef<number | null>(null);
  const geometry = useRef({ top: 0, height: 0 });
  const render = (nextValue: number) => {
    current.current = normalize(nextValue);
    const percent = Math.round(current.current * 100);
    track.current?.style.setProperty("--volume-progress", `${current.current * 100}%`);
    track.current?.setAttribute("aria-valuenow", String(percent));
    track.current?.setAttribute("aria-valuetext", `${percent}%`);
    if (percentText.current) percentText.current.textContent = `${percent}%`;
  };
  const preview = (next: number) => { render(next); onPreview(current.current); };
  const fromY = (clientY: number) => {
    if (geometry.current.height <= 0) return;
    preview((geometry.current.top + geometry.current.height - clientY) / geometry.current.height);
  };
  const down = (event: PointerEvent<HTMLDivElement>) => {
    if (event.pointerType === "mouse" && event.button !== 0) return;
    const rect = track.current?.getBoundingClientRect();
    if (!rect || rect.height <= 0) return;
    event.preventDefault(); geometry.current = { top: rect.top, height: rect.height }; pointer.current = event.pointerId;
    track.current?.focus({ preventScroll: true }); track.current?.classList.add("dragging"); track.current?.setPointerCapture(event.pointerId); fromY(event.clientY);
  };
  const move = (event: PointerEvent<HTMLDivElement>) => { if (pointer.current === event.pointerId) { event.preventDefault(); fromY(event.clientY); } };
  const finish = (event: PointerEvent<HTMLDivElement>, commit: boolean) => {
    if (pointer.current !== event.pointerId) return;
    if (commit) { fromY(event.clientY); onCommit(current.current); } else { render(value); onPreview(value); }
    if (track.current?.hasPointerCapture(event.pointerId)) track.current.releasePointerCapture(event.pointerId);
    track.current?.classList.remove("dragging"); pointer.current = null; geometry.current.height = 0;
  };
  const keydown = (event: KeyboardEvent<HTMLDivElement>) => {
    const values: Record<string, number> = { ArrowUp: current.current + .05, ArrowRight: current.current + .05, ArrowDown: current.current - .05, ArrowLeft: current.current - .05, Home: 0, End: 1 };
    if (!(event.key in values)) return;
    event.preventDefault(); preview(values[event.key]!); onCommit(current.current);
  };
  useEffect(() => { if (pointer.current === null) render(value); }, [value]);
  return <div className="volume-slider"><div ref={track} className="volume-track" role="slider" tabIndex={0} aria-label="音量" aria-orientation="vertical" aria-valuemin={0} aria-valuemax={100} onPointerDown={down} onPointerMove={move} onPointerUp={(event) => finish(event, true)} onPointerCancel={(event) => finish(event, false)} onKeyDown={keydown}><div className="volume-runway"><div className="volume-fill" /><span className="volume-thumb" aria-hidden="true" /></div></div><span ref={percentText} className="volume-percent">{Math.round(normalize(value) * 100)}%</span></div>;
}

// src/components/VolumeSlider.vue
<template>
  <div class="volume-slider">
    <div
      ref="track"
      class="volume-track"
      role="slider"
      tabindex="0"
      aria-label="音量"
      aria-orientation="vertical"
      aria-valuemin="0"
      aria-valuemax="100"
      @pointerdown="handlePointerDown"
      @pointermove="handlePointerMove"
      @pointerup="handlePointerUp"
      @pointercancel="handlePointerCancel"
      @keydown="handleKeydown"
    >
      <div class="volume-runway">
        <div class="volume-fill" />
        <span class="volume-thumb" aria-hidden="true" />
      </div>
    </div>
    <span ref="percentText" class="volume-percent">{{ initialPercent }}%</span>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  modelValue: number;
}>();

const emit = defineEmits<{
  preview: [value: number];
  commit: [value: number];
}>();

const normalizeVolume = (value: number) => Math.min(1, Math.max(0, value));
const track = ref<HTMLElement | null>(null);
const percentText = ref<HTMLElement | null>(null);
const initialPercent = Math.round(normalizeVolume(props.modelValue) * 100);
let currentVolume = normalizeVolume(props.modelValue);
let activePointerId: number | null = null;
let trackTop = 0;
let trackHeight = 0;

const renderVolume = (value: number) => {
  currentVolume = normalizeVolume(value);
  const percent = Math.round(currentVolume * 100);
  track.value?.style.setProperty("--volume-progress", `${currentVolume * 100}%`);
  track.value?.setAttribute("aria-valuenow", String(percent));
  track.value?.setAttribute("aria-valuetext", `${percent}%`);
  if (percentText.value) percentText.value.textContent = `${percent}%`;
};

const previewVolume = (value: number) => {
  renderVolume(value);
  emit("preview", currentVolume);
};

const updateFromClientY = (clientY: number) => {
  if (trackHeight <= 0) return;
  previewVolume((trackTop + trackHeight - clientY) / trackHeight);
};

const handlePointerDown = (event: PointerEvent) => {
  if (event.pointerType === "mouse" && event.button !== 0) return;
  event.preventDefault();
  const rect = track.value?.getBoundingClientRect();
  if (!rect || rect.height <= 0) return;
  trackTop = rect.top;
  trackHeight = rect.height;
  activePointerId = event.pointerId;
  track.value?.focus({ preventScroll: true });
  track.value?.classList.add("dragging");
  track.value?.setPointerCapture(event.pointerId);
  updateFromClientY(event.clientY);
};

const handlePointerMove = (event: PointerEvent) => {
  if (activePointerId !== event.pointerId) return;
  event.preventDefault();
  updateFromClientY(event.clientY);
};

const finishPointer = (event: PointerEvent, commit: boolean) => {
  if (activePointerId !== event.pointerId) return;
  if (commit) {
    updateFromClientY(event.clientY);
    emit("commit", currentVolume);
  } else {
    renderVolume(props.modelValue);
    emit("preview", currentVolume);
  }
  if (track.value?.hasPointerCapture(event.pointerId)) {
    track.value.releasePointerCapture(event.pointerId);
  }
  track.value?.classList.remove("dragging");
  activePointerId = null;
  trackHeight = 0;
};

const handlePointerUp = (event: PointerEvent) => finishPointer(event, true);
const handlePointerCancel = (event: PointerEvent) => finishPointer(event, false);

const handleKeydown = (event: KeyboardEvent) => {
  let nextVolume: number | null = null;
  switch (event.key) {
    case "ArrowUp":
    case "ArrowRight":
      nextVolume = currentVolume + 0.05;
      break;
    case "ArrowDown":
    case "ArrowLeft":
      nextVolume = currentVolume - 0.05;
      break;
    case "Home":
      nextVolume = 0;
      break;
    case "End":
      nextVolume = 1;
      break;
  }
  if (nextVolume === null) return;
  event.preventDefault();
  previewVolume(nextVolume);
  emit("commit", currentVolume);
};

watch(
  () => props.modelValue,
  (value) => {
    if (activePointerId === null) renderVolume(value);
  },
);

onMounted(() => renderVolume(currentVolume));
</script>

<style lang="scss" scoped>
.volume-slider {
  width: 100%;
  height: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-between;
}

.volume-track {
  --volume-progress: 0%;
  position: relative;
  width: 32px;
  height: 88px;
  flex: 0 0 88px;
  cursor: pointer;
  touch-action: none;
  user-select: none;

  &:focus-visible {
    outline: none;

    .volume-runway {
      box-shadow: 0 0 0 2px rgba(from var(--player-slider-main-color) r g b / 0.28);
    }
  }
}

.volume-runway {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 50%;
  width: 4px;
  border-radius: 999px;
  background: var(--player-slider-runway-color);
  transform: translateX(-50%);
}

.volume-fill {
  position: absolute;
  right: 0;
  bottom: 0;
  left: 0;
  height: var(--volume-progress);
  border-radius: inherit;
  background: var(--player-slider-main-color);
}

.volume-thumb {
  position: absolute;
  bottom: var(--volume-progress);
  left: 50%;
  width: 12px;
  height: 12px;
  border: 0;
  border-radius: 50%;
  background: var(--player-slider-main-color);
  box-shadow: none;
  transform: translate(-50%, 50%);
  pointer-events: none;
}

.volume-percent {
  font-size: 0.66rem;
  font-variant-numeric: tabular-nums;
}

@media (prefers-reduced-motion: reduce) {
  .volume-runway {
    transition: none;
  }
}
</style>
