// src/views/Main/Left.tsx
import Message from "@/components/Message";
import SocialLinks from "@/components/SocialLinks";
import { useMainStore } from "@/store";
import "@/views/Main/Left.scss";

export default function MainLeft({ onOpenOwnerPanel }: { onOpenOwnerPanel: () => void }) {
  const mobileOpen = useMainStore((state) => state.mobileOpenState);
  return <div className={`left${mobileOpen ? " hidden" : ""}`}><Message onOpenOwnerPanel={onOpenOwnerPanel} /><SocialLinks /></div>;
}

// src/views/Main/Left.vue
<template>
  <div :class="store.mobileOpenState ? 'left hidden' : 'left'">
    <Message @open-owner-panel="emit('open-owner-panel')" />
    <SocialLinks />
  </div>
</template>

<script setup lang="ts">
import { mainStore } from "@/store";
import Message from "@/components/Message.vue";
import SocialLinks from "@/components/SocialLinks.vue";
const emit = defineEmits<{
  openOwnerPanel: [];
}>();
const store = mainStore();
</script>

<style lang="scss" scoped>
.left {
  // flex: 1 0 0%;
  width: 50%;
  margin-right: 10px;
  transform: translateY(20px);
  &.hidden {
    display: none;
  }
  @media (max-width: 720px) {
    margin-right: 0;
    width: 100%;
  }
}
</style>
