// src/views/Box/index.vue
<template>
  <div class="box cards" @mouseenter="closeShow = true" @mouseleave="closeShow = false">
    <transition name="el-fade-in-linear">
      <close-one
        class="close"
        theme="filled"
        size="28"
        fill="var(--close-icon-color)"
        v-show="closeShow"
        @click="store.boxOpenState = false"
      />
    </transition>
    <div class="content">
      <!-- 可在此处自定义任意内容 -->
      <TimeCapsule />
      <MoreContent />
    </div>
  </div>
</template>

<script setup lang="ts">
import { CloseOne } from "@icon-park/vue-next";
import { mainStore } from "@/store";
import TimeCapsule from "@/components/TimeCapsule.vue";
import MoreContent from "@/components/MoreContent.vue";

const store = mainStore();
const closeShow = ref(false);
</script>

<style lang="scss" scoped>
.box {
  flex: 1 0 0%;
  margin-left: 0.75rem;
  height: 80%;
  max-width: 50%;
  position: relative;
  animation: fade 0.5s;
  overflow: hidden;

  &:hover {
    transform: scale(1);
  }

  .close {
    position: absolute;
    top: 14px;
    right: 14px;
    width: 28px;
    height: 28px;
    transition:
      transform 0.3s,
      opacity 0.3s;

    &:hover {
      transform: scale(1.2);
    }

    &:active {
      transform: scale(1);
    }
  }

  .content {
    display: flex;
    flex-direction: column;
    overflow: hidden;
    padding: 30px;
    width: 100%;
    height: 100%;
  }
}
</style>

// src/views/Box/index.tsx
import { CloseOne } from "@icon-park/react";
import { useMainStore } from "@/store";
import TimeCapsule from "@/components/TimeCapsule";
import "@/views/Box/index.scss";

export default function Box() {
  const patch = useMainStore((state) => state.patch);
  return (
    <div className="box cards">
      <CloseOne className="close" theme="filled" size="28" fill="var(--close-icon-color)" onClick={() => patch({ boxOpenState: false })} />
      <div className="content"><TimeCapsule /></div>
    </div>
  );
}
